Add version switch to CLI
input-output-hk/bech32 pull request #30
Opened 2020-12-16 23:39 UTC by newhoggy

2020-12-16 23:51 UTC, newhoggy commented
Examples:

```
$ bech32 --help
Usage: bech32 [PREFIX | (-v|--version)]
  Convert to and from bech32 strings. Data are read from standard input.

Available options:
  -h,--help                Show this help text
  PREFIX                   output version information and exit

Supported encoding formats: Base16, Bech32 & Base58.

Examples:
  To Bech32:
    $ bech32 base16_ <<< 706174617465
    base16_1wpshgct5v5r5mxh0

    $ bech32 base58_ <<< Ae2tdPwUPEYy
    base58_1p58rejhd9592uusa8pzj2

    $ bech32 new_prefix <<< old_prefix1wpshgcg2s33x3
    new_prefix1wpshgcgeak9mv

  From Bech32:
    $ bech32 <<< base16_1wpshgct5v5r5mxh0
    706174617465
$ bech32 --version
1.1.0
$ bech32 base16_ <<< 706174617465
base16_1wpshgct5v5r5mxh0
```

2020-12-16 23:55 UTC, newhoggy commented
This addresses https://github.com/input-output-hk/bech32/issues/23

2020-12-17 02:19 UTC, rvl requested changes
Thanks! I was wanting this switch do be added.

True to the parable of the bike shed, I have a few changes requested!

2020-12-17 02:19 UTC, rvl commented on bech32/app/Main.hs
> +    cmd = (RunCmd <$> optional hrpArgument) <|> (VersionCmd <$ versionSwitch)
This looks a bit odd.
```
bech32 [PREFIX | (-v|--version)]
```
Can you hide the `--version` flag from the usage text, but still have it shown in the options list?
I _think_ the modifier is [Options.Applicative.hidden](https://hackage.haskell.org/package/optparse-applicative-0.14.2.0/docs/Options-Applicative.html#v:hidden).

2020-12-17 02:19 UTC, rvl commented on bech32/app/Main.hs
> +versionSwitch :: Parser Bool
I think that `--version` is actually a flag not a switch. That is, this type should be `Parser ()`, or perhaps `Parser Cmd`.

2020-12-17 02:19 UTC, rvl commented on bech32/app/Main.hs
> +        [ text "output version information and exit"
What's going on here?

2020-12-17 02:19 UTC, rvl commented on bech32/app/Main.hs
> +import qualified Options.Applicative as OA
The coding style of this module uses less qualified imports.
I don't think there need to be any more qualified imports than what there currently are.
Even `import Paths_bech32 (version)` is fine.

2020-12-17 02:19 UTC, rvl commented on bech32/app/Main.hs
> +    VersionCmd -> IO.putStrLn . L.intercalate "." $ fmap show (versionBranch P.version)
You can just use `Data.Version.showVersion` and `putStrLn` from prelude.

2020-12-17 02:19 UTC, rvl commented on bech32/app/Main.hs
> +    ]
```suggestion
    , help "output version information and exit"
    ]
```

2020-12-17 02:19 UTC, rvl commented on bech32/app/Main.hs
> +    | VersionCmd
Record fields in sum type are totally OK by me for this type of usage.

2020-12-17 03:40 UTC, newhoggy commented on bech32/app/Main.hs
> +        [ text "output version information and exit"
Oops

2020-12-17 05:24 UTC, rvl approved these changes
Looks fine now, thanks.

I also saw there is a slightly nicer way to do the version option, if you're interesting in trying that: https://www.fpcomplete.com/haskell/library/optparse-applicative/

2020-12-17 05:39 UTC, newhoggy commented
> I also saw there is a slightly nicer way to do the version option, if you're interesting in trying that

Maybe later 😁

2020-12-17 05:39 UTC, merged